version: "3.3"

services:

  descriptions:
    restart: on-failure
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/petco/description_directions_attributes_
    ports:
      - "3002:3002"
    links:
      - "mongo"
      - "redis"
    command: bash -c "wait-for-it.sh mongo:27017 && wait-for-it.sh redis:6379 && npm install && npm run dev"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/Users/samjohnson/Documents/hrfiles/petco/description_directions_attributes_

  mongo:
    restart: always
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./data:/data
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"