version: "3.3"

services:

  descriptions:
    restart: on-failure
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/petco/description_directions_attributes_
    ports:
      - "80:3002"
    command: bash -c "npm install && npm run pro"
    volumes:
      - ./:/Users/samjohnson/Documents/hrfiles/petco/description_directions_attributes_