version: '3'
services:
  web:
    image: descriptionservice
    build: .
    command: "node start.js"
    command: "node seed.js"
    ports:
      - "3002:3002"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
