version '3.3'

services:

  descriptions:
    restart: on-failure
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/petco/description_directions_attributes_
    ports:
      - "80:3002"
    links:
      - "db"
    command: bash -c "wait-for-it.sh mongo:27017 && npm install && npm run dev:start"